import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { copyFile, mkdir, rm } from "fs/promises";
import path from "path";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
*/
`;

const pluginId = "gpt4free-text-generator-plugin";
const rootDir = process.cwd();
const prod = process.argv.includes("production");
const watch = !prod;
const targetArg = process.argv.find((arg) => arg.startsWith("--target="));
const target = targetArg ? targetArg.slice("--target=".length) : "desktop";

const packageDir = path.join(rootDir, "build", target === "android" ? "android" : pluginId);
const outfile = path.join(packageDir, "main.js");

async function copyStaticFiles() {
  await mkdir(packageDir, { recursive: true });
  await copyFile(path.join(rootDir, "manifest.json"), path.join(packageDir, "manifest.json"));
}

if (!watch) {
  await rm(packageDir, { recursive: true, force: true });
}
await copyStaticFiles();

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins,
  ],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile,
  plugins: [
    {
      name: "css-inline",
      setup(build) {
        build.onLoad({ filter: /\.css$/ }, async (args) => {
          const fs = await import("fs/promises");
          const css = await fs.readFile(args.path, "utf8");
          const contents = `
            const style = document.createElement('style');
            style.textContent = ${JSON.stringify(css)};
            document.head.appendChild(style);
          `;
          return { contents, loader: "js" };
        });
      },
    },
  ],
});

if (prod) {
  await context.rebuild();
  await copyStaticFiles();
  await context.dispose();
  console.log(`Build completed: ${outfile}`);
  process.exit(0);
}

await context.watch();
console.log(`Watching. Output directory: ${packageDir}`);
