import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { copyFile, mkdir, rm } from "fs/promises";
import path from "path";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
*/
`;

const pluginId = "gpt4free-text-generator-plugin";
const rootDir = process.cwd();
const prod = process.argv.includes("production");
const watch = !prod;
const targetArg = process.argv.find((arg) => arg.startsWith("--target="));
const target = targetArg ? targetArg.slice("--target=".length) : "desktop";

const packageDir = path.join(rootDir, "build", target === "android" ? "android" : pluginId);
const outfile = path.join(packageDir, "main.js");

async function copyStaticFiles() {
  await mkdir(packageDir, { recursive: true });
  await copyFile(path.join(rootDir, "manifest.json"), path.join(packageDir, "manifest.json"));
  // Use the vendored FTS5-enabled sql.js wasm (see vendor/sqljs-fts5/README.md).
  // The upstream npm sql.js wasm does NOT include FTS5, which RetrievalDatabase requires.
  await copyFile(
    path.join(rootDir, "vendor", "sqljs-fts5", "sql-wasm.wasm"),
    path.join(packageDir, "sql-wasm.wasm")
  );
}

if (!watch) {
  await rm(packageDir, { recursive: true, force: true });
}
await copyStaticFiles();

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins,
  ],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile,
  // Alias `sql.js` to the vendored FTS5-enabled loader. The upstream npm
  // sql.js JS loader is built against a different Emscripten version than
  // our FTS5 wasm; mixing them produces "file is not a database". Both the
  // JS loader and wasm binary MUST come from the same build.
  // See vendor/sqljs-fts5/README.md for provenance.
  //
  // We use an onLoad plugin rather than `alias` because the vendored file is
  // a UMD/CJS module that assigns `exports["Module"] = initSqlJs` and has no
  // ESM `default` export. The plugin wraps the source so `import initSqlJs
  // from 'sql.js'` resolves to the initSqlJs function.
  plugins: [
    {
      name: "sqljs-fts5-alias",
      setup(build) {
        const sqlJsPath = path.join(rootDir, "vendor", "sqljs-fts5", "sql-wasm.js");
        build.onResolve({ filter: /^sql\.js$/ }, () => ({
          path: sqlJsPath,
          namespace: "sqljs-fts5",
        }));
        build.onLoad({ filter: /.*/, namespace: "sqljs-fts5" }, async () => {
          const fs = await import("fs/promises");
          let source = await fs.readFile(sqlJsPath, "utf8");

          // Patch: inject wasmBinary support into the vendored Emscripten loader.
          // This build (Emscripten 6.0.3) pre-dates the `wasmBinary` config option
          // that newer sql.js builds support. In Obsidian's Electron renderer,
          // `fetch()` of `file://` URLs is blocked and `fs` is unavailable, so
          // the only way to load the wasm is via `wasmBinary` (read from the vault
          // adapter). We patch the `Va` function (the wasm instantiation entry
          // point) to check `Module.wasmBinary` before attempting any fetch.
          //
          // Original:  async function Va(a){var b=Sa;if(!Da(b)&&!ca)try{...fetch...}catch{...}return Ua(b,a)}
          // Patched:   checks Module.wasmBinary first, uses WebAssembly.instantiate directly
          source = source.replace(
            'async function Va(a){var b=Sa;if(!Da(b)&&!ca)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){C(`wasm streaming compile failed: ${d}`),C("falling back to ArrayBuffer instantiation")}return Ua(b,a)}',
            'async function Va(a){var b=Sa;if(l.wasmBinary){var __wasmBytes=l.wasmBinary;if(__wasmBytes instanceof ArrayBuffer)__wasmBytes=new Uint8Array(__wasmBytes);return await WebAssembly.instantiate(__wasmBytes,a)}if(!Da(b)&&!ca)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){C(`wasm streaming compile failed: ${d}`),C("falling back to ArrayBuffer instantiation")}return Ua(b,a)}'
          );

          // Wrap the UMD source so it runs in a CJS context (with module/exports/
          // require) and then re-export the initSqlJs function as ESM default.
          // The UMD wrapper assigns exports["Module"] = initSqlJs in CJS.
          const contents = [
            'let moduleObj = { exports: {} };',
            'let exports = moduleObj.exports;',
            'const __require = (id) => {',
            '  if (id === "node:fs" || id === "fs") return require("fs");',
            '  if (id === "node:path" || id === "path") return require("path");',
            '  return require(id);',
            '};',
            '// The UMD source references require and module/exports on the',
            '// Node sync-load path. Provide them as writable bindings.',
            'let module = moduleObj;',
            'let require = __require;',
            source,
            'const __rawInitSqlJs = moduleObj.exports.Module || moduleObj.exports.default;',
            '// Wrap initSqlJs to reset the singleton promise on failure, so a',
            '// transient failure (e.g. wasm load error) does not poison all',
            '// subsequent callers sharing the same module instance.',
            '// `initSqlJsPromise` is a module-level var in the vendored source above.',
            'const __initSqlJs = (config) => {',
            '  const p = __rawInitSqlJs(config);',
            '  if (p && typeof p.catch === "function") {',
            '    p.catch(() => { initSqlJsPromise = undefined; });',
            '  }',
            '  return p;',
            '};',
            'export default __initSqlJs;',
          ].join('\n');
          return { contents, loader: "js", resolveDir: path.dirname(sqlJsPath) };
        });
      },
    },
    {
      name: "css-inline",
      setup(build) {
        build.onLoad({ filter: /\.css$/ }, async (args) => {
          const fs = await import("fs/promises");
          const css = await fs.readFile(args.path, "utf8");
          const contents = `
            const style = document.createElement('style');
            style.textContent = ${JSON.stringify(css)};
            document.head.appendChild(style);
          `;
          return { contents, loader: "js" };
        });
      },
    },
  ],
});

if (prod) {
  await context.rebuild();
  await copyStaticFiles();
  await context.dispose();
  console.log(`Build completed: ${outfile}`);
  process.exit(0);
}

await context.watch();
console.log(`Watching. Output directory: ${packageDir}`);
