import { App, normalizePath, TFile } from 'obsidian';
import { readdir, readFile, stat } from 'fs/promises';
import path from 'path';
import { PluginSettings } from '../types';
import { StudySourceContext, StudySourceContextFile, StudySourceFile, StudySourceGroup, StudySourceScanResult } from '../types/studySources';

export class StudySourceLibrary {
  constructor(
    private app: App,
    private settings: PluginSettings
  ) {}

  updateSettings(settings: PluginSettings): void {
    this.settings = settings;
  }

  async scan(): Promise<StudySourceScanResult> {
    const files: StudySourceFile[] = [];
    const groups = [...this.settings.studySourceGroups]
      .filter((group) => group.enabled)
      .sort((a, b) => a.priority - b.priority);

    for (const group of groups) {
      const groupFiles = await this.scanGroup(group);
      files.push(...groupFiles);
    }

    return {
      scannedAt: new Date().toISOString(),
      groups: this.settings.studySourceGroups,
      files,
      totalFiles: files.length,
      includedFiles: files.filter((file) => file.included).length,
      totalEstimatedTokens: files.reduce((sum, file) => sum + file.estimatedTokens, 0),
      includedEstimatedTokens: files.filter((file) => file.included).reduce((sum, file) => sum + file.estimatedTokens, 0),
    };
  }

  async createOrUpdateInventoryNote(result: StudySourceScanResult): Promise<TFile> {
    const notePath = normalizePath(this.settings.studySourceInventoryNotePath || 'WikiSynthesis/Study/Source Library/Study Source Inventory.md');
    await this.ensureVaultFolder(path.posix.dirname(notePath));
    const content = this.renderInventoryMarkdown(result);
    const existing = this.app.vault.getAbstractFileByPath(notePath);

    if (existing instanceof TFile) {
      await this.app.vault.modify(existing, content);
      return existing;
    }

    return await this.app.vault.create(notePath, content);
  }

  async buildContext(result: StudySourceScanResult, maxEstimatedTokens: number): Promise<StudySourceContext> {
    const files: StudySourceContextFile[] = [];
    let estimatedTokens = 0;
    let skippedFiles = 0;

    const included = result.files
      .filter((file) => file.included)
      .sort((a, b) => {
        const groupPriorityA = result.groups.find((group) => group.id === a.groupId)?.priority ?? 9999;
        const groupPriorityB = result.groups.find((group) => group.id === b.groupId)?.priority ?? 9999;
        return groupPriorityA - groupPriorityB || a.relativePath.localeCompare(b.relativePath);
      });

    for (const file of included) {
      if (estimatedTokens + file.estimatedTokens > maxEstimatedTokens) {
        skippedFiles++;
        continue;
      }

      try {
        const content = await readFile(file.path, 'utf8');
        files.push({ ...file, content });
        estimatedTokens += file.estimatedTokens;
      } catch {
        skippedFiles++;
      }
    }

    return { files, estimatedTokens, skippedFiles };
  }

  renderInventoryMarkdown(result: StudySourceScanResult): string {
    const groupSections = result.groups
      .sort((a, b) => a.priority - b.priority)
      .map((group) => this.renderGroupSection(result, group))
      .join('\n\n');

    return [
      '# Study Source Inventory',
      '',
      `Generated: ${result.scannedAt}`,
      '',
      'This note is generated by the LLM Automation plugin. It shows which local study sources are configured and which files are currently included for LLM context building.',
      '',
      '## Summary',
      '',
      `- Configured groups: ${result.groups.length}`,
      `- Scanned files: ${result.totalFiles}`,
      `- Included files: ${result.includedFiles}`,
      `- Total estimated tokens: ${result.totalEstimatedTokens}`,
      `- Included estimated tokens: ${result.includedEstimatedTokens}`,
      '',
      groupSections,
      '',
    ].join('\n');
  }

  private async scanGroup(group: StudySourceGroup): Promise<StudySourceFile[]> {
    if (!group.path.trim()) {
      return [];
    }

    const extensions = new Set(group.extensions.map((extension) => extension.toLowerCase().replace(/^\./, '')));
    const discovered = await this.discoverFiles(group.path, group.recursive);
    const files: StudySourceFile[] = [];
    let includedCount = 0;
    let includedTokens = 0;

    for (const filePath of discovered.sort((a, b) => a.localeCompare(b))) {
      const extension = path.extname(filePath).replace(/^\./, '').toLowerCase();
      if (extensions.size > 0 && !extensions.has(extension)) {
        continue;
      }

      const fileInfo = await this.readFileInfo(group, filePath, extension);
      if (!fileInfo) {
        continue;
      }

      if (includedCount >= group.maxFiles) {
        fileInfo.included = false;
        fileInfo.skippedReason = `group max files reached (${group.maxFiles})`;
      } else if (includedTokens + fileInfo.estimatedTokens > group.maxEstimatedTokens) {
        fileInfo.included = false;
        fileInfo.skippedReason = `group token budget reached (${group.maxEstimatedTokens})`;
      } else {
        fileInfo.included = true;
        includedCount++;
        includedTokens += fileInfo.estimatedTokens;
      }

      files.push(fileInfo);
    }

    return files;
  }

  private async discoverFiles(rootPath: string, recursive: boolean): Promise<string[]> {
    const info = await this.safeStat(rootPath);
    if (!info) {
      return [];
    }

    if (info.isFile()) {
      return [rootPath];
    }

    if (!info.isDirectory()) {
      return [];
    }

    const results: string[] = [];
    const entries = await this.safeReadDir(rootPath);
    for (const entry of entries) {
      const entryPath = path.join(rootPath, entry.name);
      if (entry.isDirectory()) {
        if (this.shouldSkipDirectory(entry.name)) {
          continue;
        }
        if (recursive) {
          results.push(...await this.discoverFiles(entryPath, true));
        }
      } else if (entry.isFile()) {
        results.push(entryPath);
      }
    }

    return results;
  }

  private async readFileInfo(group: StudySourceGroup, filePath: string, extension: string): Promise<StudySourceFile | null> {
    try {
      const fileStat = await stat(filePath);
      const content = await readFile(filePath, 'utf8');

      return {
        groupId: group.id,
        groupName: group.name,
        type: group.type,
        path: filePath,
        relativePath: path.relative(group.path, filePath) || path.basename(filePath),
        extension,
        sizeBytes: fileStat.size,
        charCount: content.length,
        estimatedTokens: this.estimateTokens(content),
        included: false,
      };
    } catch {
      return null;
    }
  }

  private estimateTokens(content: string): number {
    return Math.ceil(content.length / 4);
  }

  private shouldSkipDirectory(name: string): boolean {
    const normalized = name.toLowerCase();
    return normalized === '.git'
      || normalized === 'node_modules'
      || normalized === 'bin'
      || normalized === 'obj'
      || normalized === '.vs';
  }

  private async safeStat(targetPath: string) {
    try {
      return await stat(targetPath);
    } catch {
      return null;
    }
  }

  private async safeReadDir(targetPath: string) {
    try {
      return await readdir(targetPath, { withFileTypes: true });
    } catch {
      return [];
    }
  }

  private async ensureVaultFolder(folderPath: string): Promise<void> {
    const normalized = normalizePath(folderPath);
    if (!normalized || normalized === '.') {
      return;
    }

    const parts = normalized.split('/');
    let current = '';
    for (const part of parts) {
      current = current ? `${current}/${part}` : part;
      if (!await this.app.vault.adapter.exists(current)) {
        await this.app.vault.createFolder(current);
      }
    }
  }

  private renderGroupSection(result: StudySourceScanResult, group: StudySourceGroup): string {
    const files = result.files.filter((file) => file.groupId === group.id);
    const included = files.filter((file) => file.included);
    const includedTokens = included.reduce((sum, file) => sum + file.estimatedTokens, 0);
    const skipped = files.filter((file) => !file.included);

    const rows = files
      .slice(0, 200)
      .map((file) => `| ${file.included ? 'yes' : 'no'} | ${this.escapeTable(file.relativePath)} | ${file.estimatedTokens} | ${file.skippedReason ?? ''} |`)
      .join('\n');

    return [
      `## ${group.name}`,
      '',
      `- Enabled: ${group.enabled}`,
      `- Type: ${group.type}`,
      `- Path: \`${group.path}\``,
      `- Files found: ${files.length}`,
      `- Files included: ${included.length}`,
      `- Files skipped: ${skipped.length}`,
      `- Included estimated tokens: ${includedTokens}`,
      `- Group max files: ${group.maxFiles}`,
      `- Group max estimated tokens: ${group.maxEstimatedTokens}`,
      '',
      '| Included | File | Estimated tokens | Skipped reason |',
      '| --- | --- | ---: | --- |',
      rows || '|  | No files found |  |  |',
      files.length > 200 ? `\n\nOnly first 200 files shown for this group.` : '',
    ].join('\n');
  }

  private escapeTable(value: string): string {
    return value.replace(/\|/g, '\\|');
  }
}
